(()=>{
const DB="hanafi-media-artwork",POSTERS="posters",SETTINGS="settings",VERSION=2;
function openDB(){return new Promise((ok,no)=>{const r=indexedDB.open(DB,VERSION);r.onupgradeneeded=()=>{const d=r.result;if(!d.objectStoreNames.contains(POSTERS))d.createObjectStore(POSTERS);if(!d.objectStoreNames.contains(SETTINGS))d.createObjectStore(SETTINGS)};r.onsuccess=()=>ok(r.result);r.onerror=()=>no(r.error)})}
async function get(store,key){const d=await openDB();return new Promise(ok=>{const r=d.transaction(store).objectStore(store).get(key);r.onsuccess=()=>ok(r.result??null);r.onerror=()=>ok(null)})}
async function put(store,key,value){const d=await openDB();return new Promise((ok,no)=>{const r=d.transaction(store,"readwrite").objectStore(store).put(value,key);r.onsuccess=()=>ok();r.onerror=()=>no(r.error)})}
async function del(store,key){const d=await openDB();return new Promise(ok=>{const r=d.transaction(store,"readwrite").objectStore(store).delete(key);r.onsuccess=()=>ok();r.onerror=()=>ok()})}
const settingKey=id=>"artwork-setting:"+id,customKey=id=>"custom-artwork:"+id,LIBRARY_HANDLE="movie-art-folder";
async function setting(id){return await get(SETTINGS,settingKey(id))}
async function getArtworkFolder(){return await get(SETTINGS,LIBRARY_HANDLE)}
async function chooseArtworkFolder(){if(!window.showDirectoryPicker)throw Error("This browser does not support folder access.");const h=await window.showDirectoryPicker({mode:"read"});await put(SETTINGS,LIBRARY_HANDLE,h);return h}
function normName(s){return String(s||"").toLowerCase().normalize("NFD").replace(/[\u0300-\u036f]/g,"").replace(/[^a-z0-9]+/g," ").trim()}
async function localFolderMatch(m){const h=await getArtworkFolder();if(!h)return null;try{if((await h.queryPermission({mode:"read"}))!=="granted"&&(await h.requestPermission({mode:"read"}))!=="granted")return null;const title=normName(m.title),year=String(m.year||"");let best=null,score=-1;for await(const entry of h.values()){if(entry.kind!=="file"||!/\.(jpe?g|png|webp)$/i.test(entry.name))continue;const n=normName(entry.name.replace(/\.[^.]+$/,""));let s=0;if(n.includes(title))s+=10;if(year&&n.includes(year))s+=4;for(const a of (m.aliases||[]))if(n.includes(normName(a)))s+=6;if(s>score){score=s;best=entry}}if(best&&score>=10){const file=await best.getFile(),b=await normalize(file);await put(POSTERS,customKey(m.id),b);await put(SETTINGS,settingKey(m.id),{mode:"local",locked:true,crop:{scale:1,x:"50%",y:"50%"},matchedFile:best.name});return{url:URL.createObjectURL(b),crop:{scale:1,x:"50%",y:"50%"},locked:true,matchedFile:best.name}}}catch{}return null}
async function sourceURL(a){let u=a.url;if(!u&&a.provider==="commons"){const r=await fetch("https://commons.wikimedia.org/w/api.php?action=query&format=json&origin=*&prop=imageinfo&iiprop=url&iiurlwidth=700&titles=File:"+encodeURIComponent(a.file));if(r.ok){const j=await r.json(),p=Object.values(j.query?.pages||{})[0],i=p?.imageinfo?.[0];u=i?.thumburl||i?.url}}if(!u&&a.provider==="wikipedia"){const r=await fetch("https://en.wikipedia.org/api/rest_v1/page/summary/"+encodeURIComponent(a.page));if(r.ok){const j=await r.json();u=j.thumbnail?.source||j.originalimage?.source}}return u||null}
async function blobURL(key,url){const cached=await get(POSTERS,key);if(cached instanceof Blob)return URL.createObjectURL(cached);if(!url)return null;try{const r=await fetch(url);if(!r.ok)throw Error();const b=await r.blob();await put(POSTERS,key,b);return URL.createObjectURL(b)}catch{return url}}
async function resolve(m){const s=await setting(m.id);if(s?.mode==="local"){const b=await get(POSTERS,customKey(m.id));if(b)return{url:URL.createObjectURL(b),crop:s.crop||{},locked:true}}if(s?.sourceUrl){return{url:await blobURL(customKey(m.id),s.sourceUrl),crop:s.crop||{},locked:!!s.locked}}const local=await localFolderMatch(m);if(local)return local;const u=await sourceURL(m.artwork);return{url:await blobURL(m.artwork.cacheKey,u),crop:{scale:m.artwork.scale||1,x:m.artwork.x||"50%",y:m.artwork.y||"50%"},locked:false}}
function styles(){if(document.getElementById("hanafi-artwork-manager-style"))return;const s=document.createElement("style");s.id="hanafi-artwork-manager-style";s.textContent=`
.art-edit{border:1px solid rgba(216,181,96,.4);background:#171717;color:#f3d989;border-radius:9px;padding:.55rem .8rem;cursor:pointer}
.art-modal{position:fixed;inset:0;z-index:1000;background:rgba(0,0,0,.86);display:grid;place-items:center;padding:1rem}.art-modal[hidden]{display:none}.art-box{width:min(980px,100%);max-height:92vh;overflow:auto;background:#0d1511;border:1px solid #d8b560;border-radius:16px;padding:1rem}.art-head{display:flex;justify-content:space-between;gap:1rem;align-items:center}.art-head button,.art-actions button,.art-search button{border:1px solid rgba(216,181,96,.4);background:#171717;color:#eee;border-radius:8px;padding:.55rem .75rem;cursor:pointer}.art-grid{display:grid;grid-template-columns:240px 1fr;gap:1rem}.art-preview{aspect-ratio:2/3;background:#050706;border:1px solid rgba(216,181,96,.35);border-radius:12px;overflow:hidden}.art-preview img{width:100%;height:100%;object-fit:cover;transform:scale(var(--scale,1));object-position:var(--x,50%) var(--y,50%)}.art-search{display:flex;gap:.5rem;flex-wrap:wrap;margin:.8rem 0}.art-search input{flex:1;min-width:180px;background:#080b09;color:#eee;border:1px solid rgba(216,181,96,.3);border-radius:8px;padding:.6rem}.art-candidates{display:grid;grid-template-columns:repeat(auto-fill,minmax(120px,1fr));gap:.65rem}.art-candidate{background:#111;border:1px solid rgba(216,181,96,.25);border-radius:10px;padding:.35rem;color:#eee;cursor:pointer}.art-candidate img{width:100%;aspect-ratio:2/3;object-fit:cover;display:block}.art-candidate span{display:block;font-size:.72rem;padding:.3rem}.art-controls label{display:grid;grid-template-columns:80px 1fr 46px;gap:.4rem;align-items:center;margin:.5rem 0}.art-actions{display:flex;gap:.5rem;flex-wrap:wrap;margin-top:.8rem}.art-status{min-height:1.3em;color:#d8d2c2}.art-file{margin:.7rem 0}.art-folder{display:flex;gap:.5rem;align-items:center;flex-wrap:wrap;margin:.7rem 0}.art-folder small{color:#b9b3a5}@media(max-width:680px){.art-grid{grid-template-columns:1fr}.art-preview{width:min(220px,70vw);margin:auto}}`;document.head.appendChild(s)}
function modal(){styles();let m=document.getElementById("hanafiArtworkModal");if(m)return m;m=document.createElement("div");m.id="hanafiArtworkModal";m.className="art-modal";m.hidden=true;m.innerHTML=`<div class="art-box" role="dialog" aria-modal="true" aria-labelledby="artTitle"><div class="art-head"><h2 id="artTitle">Edit artwork</h2><button data-close>Close</button></div><div class="art-grid"><div><div class="art-preview"><img data-preview alt=""></div><div class="art-controls"><label>Zoom <input data-scale type="range" min="1" max="1.5" step=".01" value="1"><output data-scaleout>1.00</output></label><label>Left/Right <input data-x type="range" min="0" max="100" value="50"><output data-xout>50%</output></label><label>Up/Down <input data-y type="range" min="0" max="100" value="50"><output data-yout>50%</output></label></div><div class="art-actions"><button data-save>Use this artwork</button><button data-reset>Reset to Automatic</button></div><p class="art-status" data-status></p></div><div><div class="art-search"><input data-query type="search" aria-label="Artwork search"><button data-search>Search artwork</button></div><div class="art-search"><input data-url type="url" placeholder="Paste IMDb title link or image URL"><button data-useurl>Preview URL</button></div><div class="art-folder"><button data-folder type="button">Choose Movie Art Folder</button><small data-foldername>No artwork folder selected</small></div><div class="art-file"><label>Or choose one local image: <input data-file type="file" accept="image/jpeg,image/png,image/webp"></label></div><div class="art-candidates" data-candidates></div></div></div></div>`;document.body.appendChild(m);m.querySelector("[data-close]").onclick=()=>m.hidden=true;return m}
async function imdbArtwork(input){const m=input.match(/tt\d{5,12}/i);if(!m)return[];const id=m[0].toLowerCase(),sparql='SELECT ?item ?itemLabel ?image WHERE { ?item wdt:P345 "'+id+'". OPTIONAL { ?item wdt:P18 ?image. } SERVICE wikibase:label { bd:serviceParam wikibase:language "en". } } LIMIT 8';const r=await fetch("https://query.wikidata.org/sparql?format=json&query="+encodeURIComponent(sparql),{headers:{Accept:"application/sparql-results+json"}});if(!r.ok)throw Error("Could not resolve that IMDb title.");const j=await r.json();return j.results.bindings.filter(x=>x.image?.value).map(x=>({title:(x.itemLabel?.value||id)+" · IMDb "+id,url:x.image.value.replace("http://","https://")}))}
async function wikipediaSearch(q){const api="https://en.wikipedia.org/w/api.php?action=query&format=json&origin=*&generator=search&gsrlimit=12&gsrsearch="+encodeURIComponent(q)+"&prop=pageimages|info&pithumbsize=500&inprop=url";const r=await fetch(api);if(!r.ok)return[];const j=await r.json();return Object.values(j.query?.pages||{}).filter(p=>p.thumbnail?.source).map(p=>({title:p.title+" · Wikipedia",url:p.thumbnail.source}))}
async function commonsSearch(q){const u="https://commons.wikimedia.org/w/api.php?action=query&format=json&origin=*&generator=search&gsrnamespace=6&gsrlimit=18&gsrsearch="+encodeURIComponent(q+" poster")+"&prop=imageinfo&iiprop=url&iiurlwidth=360";const r=await fetch(u);if(!r.ok)throw Error("Artwork search failed.");const j=await r.json();return Object.values(j.query?.pages||{}).map(p=>({title:p.title.replace(/^File:/,""),url:p.imageinfo?.[0]?.thumburl||p.imageinfo?.[0]?.url})).filter(x=>x.url)}
async function artworkSearch(q){const imdb=/imdb\.com\/title\/tt\d+/i.test(q)||/^tt\d+$/i.test(q);if(imdb)return await imdbArtwork(q);const [wiki,commons]=await Promise.all([wikipediaSearch(q),commonsSearch(q)]);const seen=new Set();return [...wiki,...commons].filter(x=>x.url&&!seen.has(x.url)&&seen.add(x.url))}
async function resolveEnteredURL(u){if(/imdb\.com\/title\/tt\d+/i.test(u)){const rs=await imdbArtwork(u);if(!rs.length)throw Error("That IMDb title was found, but it has no usable artwork in the metadata source.");return rs[0]}return{title:"Manual image URL",url:u}}
async function normalize(file){const bmp=await createImageBitmap(file,{imageOrientation:"from-image"});const maxW=900,maxH=1350,ratio=Math.min(1,maxW/bmp.width,maxH/bmp.height),w=Math.max(1,Math.round(bmp.width*ratio)),h=Math.max(1,Math.round(bmp.height*ratio));const c=document.createElement("canvas");c.width=w;c.height=h;c.getContext("2d").drawImage(bmp,0,0,w,h);return await new Promise(ok=>c.toBlob(b=>ok(b||file),"image/webp",.88))}
async function open(m,onSaved){const el=modal(),img=el.querySelector("[data-preview]"),status=el.querySelector("[data-status]"),scale=el.querySelector("[data-scale]"),x=el.querySelector("[data-x]"),y=el.querySelector("[data-y]"),cands=el.querySelector("[data-candidates]");el.hidden=false;el.querySelector("#artTitle").textContent="Edit artwork · "+m.title;el.querySelector("[data-query]").value=m.title+" "+m.year;cands.innerHTML="";let chosen={kind:"current",url:null,blob:null};const current=await resolve(m);img.src=current.url||"";chosen.url=current.url;const crop=current.crop||{};scale.value=crop.scale||1;x.value=parseFloat(crop.x)||50;y.value=parseFloat(crop.y)||50;function paint(){img.style.setProperty("--scale",scale.value);img.style.setProperty("--x",x.value+"%");img.style.setProperty("--y",y.value+"%");el.querySelector("[data-scaleout]").value=Number(scale.value).toFixed(2);el.querySelector("[data-xout]").value=x.value+"%";el.querySelector("[data-yout]").value=y.value+"%"}[scale,x,y].forEach(i=>i.oninput=paint);paint();
const folder=await getArtworkFolder();el.querySelector("[data-foldername]").textContent=folder?"Artwork folder: "+folder.name:"Choose your Movie Cards folder once; Hanafi will auto-match title/year artwork from it.";
el.querySelector("[data-folder]").onclick=async()=>{status.textContent="Choose your movie-art folder…";try{const h=await chooseArtworkFolder();el.querySelector("[data-foldername]").textContent="Artwork folder: "+h.name;const found=await localFolderMatch(m);if(found){img.src=found.url;chosen={kind:"current",url:found.url,blob:null};status.textContent="Matched local artwork automatically from "+found.matchedFile+"."}else status.textContent="Folder saved. No title/year match found for this movie yet."}catch(e){status.textContent=e.message}};
el.querySelector("[data-search]").onclick=async()=>{status.textContent="Searching…";cands.innerHTML="";try{const q=el.querySelector("[data-query]").value.trim();const exact=(m.imdbId||"")+" "+m.title+" "+m.year+" "+(m.originalTitle||"")+" "+(m.director||"");const rs=await artworkSearch(q===m.title+" "+m.year?exact:q);rs.forEach(a=>{const b=document.createElement("button");b.className="art-candidate";b.innerHTML='<img alt=""><span></span>';b.querySelector("img").src=a.url;b.querySelector("span").textContent=a.title;b.onclick=()=>{chosen={kind:"url",url:a.url,blob:null};img.src=a.url;status.textContent="Candidate selected. Adjust framing, then save."};cands.appendChild(b)});status.textContent=rs.length?rs.length+" artwork candidates found.":"No candidates found. Use a URL or local image."}catch(e){status.textContent=e.message}};
el.querySelector("[data-useurl]").onclick=async()=>{const u=el.querySelector("[data-url]").value.trim();if(!u)return;status.textContent="Resolving link…";try{const a=await resolveEnteredURL(u);chosen={kind:"url",url:a.url,blob:null};img.src=a.url;status.textContent=/imdb\.com/i.test(u)?"IMDb title matched. Adjust framing, then save.":"Image URL selected. Adjust framing, then save."}catch(e){status.textContent=e.message}};
el.querySelector("[data-file]").onchange=async e=>{const file=e.target.files?.[0];if(!file)return;status.textContent="Preparing local image…";try{const b=await normalize(file);chosen={kind:"local",url:null,blob:b};img.src=URL.createObjectURL(b);status.textContent="Local image ready. Adjust framing, then save."}catch{status.textContent="Could not read that image."}};
el.querySelector("[data-save]").onclick=async()=>{status.textContent="Saving…";const crop={scale:Number(scale.value),x:x.value+"%",y:y.value+"%"};try{if(chosen.kind==="local"&&chosen.blob){await put(POSTERS,customKey(m.id),chosen.blob);await put(SETTINGS,settingKey(m.id),{mode:"local",locked:true,crop})}else if(chosen.url){let stored=false;try{const r=await fetch(chosen.url);if(r.ok){await put(POSTERS,customKey(m.id),await r.blob());stored=true}}catch{}await put(SETTINGS,settingKey(m.id),{mode:"selected",locked:true,sourceUrl:stored?null:chosen.url,crop})}status.textContent="Artwork saved and locked.";if(onSaved)await onSaved(await resolve(m))}catch{status.textContent="Artwork could not be saved."}};
el.querySelector("[data-reset]").onclick=async()=>{await del(SETTINGS,settingKey(m.id));await del(POSTERS,customKey(m.id));status.textContent="Automatic artwork restored.";const r=await resolve(m);img.src=r.url||"";scale.value=r.crop.scale||1;x.value=parseFloat(r.crop.x)||50;y.value=parseFloat(r.crop.y)||50;paint();chosen={kind:"current",url:r.url,blob:null};if(onSaved)await onSaved(r)};
}
window.HanafiArtworkManager={open,resolve,setting,chooseArtworkFolder,localFolderMatch};
})();