#!/usr/bin/env bash
set -euo pipefail

# Configure and smoke-test Hanafi Nougat Media Core against the real Hosted
# library without copying movie files into Git or another media directory.
#
# Usage from the repository root:
#   bash media-server/deploy/configure-hosted-library.sh
#
# Optional overrides:
#   HOSTED_ROOT=/path/to/Hosted \
#   MANIFEST_PATH=/path/to/media.tsv \
#   bash media-server/deploy/configure-hosted-library.sh

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
HOSTED_ROOT="${HOSTED_ROOT:-/home/dereksparks1982/Videos/Hosted}"
MANIFEST_PATH="${MANIFEST_PATH:-$HOME/.config/hanafi-media/media.tsv}"
BUILD_DIR="${BUILD_DIR:-$REPO_ROOT/build/media-server}"
PORT="${HANAFI_MEDIA_PORT:-8096}"
BIND="127.0.0.1"

AL_RISALAH="$HOSTED_ROOT/Al-Risalah"
LION="$HOSTED_ROOT/Lion of The Desert"
TEN="$HOSTED_ROOT/The Ten Commandments"

EN_720="$AL_RISALAH/The Message (1976).nosubs.mp4"
EN_1080="$AL_RISALAH/The.Message.1976.English.1080p.hardsubs.mp4"
AR_1080="$AL_RISALAH/The.Message.1976.1080p.BluRay.x264.AAC5.1.arabic.englishsubs.mp4"
AR_1080_SRT="$AL_RISALAH/The.Message.1976.1080p.BluRay.x264.AAC5.1.englishsubs.srt"
AR_1080_HARDSUBS="$AL_RISALAH/The.Message.1976.1080p.WEB-DL.DD5.1.H264.nosubs.mkv"
AR_480="$AL_RISALAH/Al-Risalah-1976-Arabic-480p.english.subs.mp4"
AR_360="$AL_RISALAH/Al-Risalah-1976-Arabic.360p.nosubs.mp4"
LION_1981="$LION/Lion-of-the-Desert-1981.nosubs.mp4"
TEN_1923="$TEN/The Ten Commandments (1923).mp4"

required=(
  "$EN_720"
  "$AR_1080"
  "$AR_1080_SRT"
  "$AR_480"
  "$AR_360"
  "$LION_1981"
  "$TEN_1923"
)

missing=0
for path in "${required[@]}"; do
  if [[ ! -f "$path" ]]; then
    printf 'MISSING: %s\n' "$path" >&2
    missing=1
  fi
done

if (( missing )); then
  echo "Hosted library is not ready. No manifest was changed." >&2
  exit 2
fi

mkdir -p "$(dirname "$MANIFEST_PATH")"
umask 077
{
  printf '# Private runtime manifest generated by configure-hosted-library.sh\n'
  printf '# id<TAB>absolute media path<TAB>MIME type<TAB>optional subtitle path\n'
  printf 'message-en-720\t%s\tvideo/mp4\t\n' "$EN_720"
  if [[ -f "$EN_1080" ]]; then
    printf 'message-en-1080-hardsubs\t%s\tvideo/mp4\t\n' "$EN_1080"
  fi
  printf 'risalah-ar-1080\t%s\tvideo/mp4\t%s\n' "$AR_1080" "$AR_1080_SRT"
  if [[ -f "$AR_1080_HARDSUBS" ]]; then
    printf 'risalah-ar-1080-hardsubs\t%s\tvideo/x-matroska\t\n' "$AR_1080_HARDSUBS"
  fi
  printf 'risalah-ar-480\t%s\tvideo/mp4\t\n' "$AR_480"
  printf 'risalah-ar-360\t%s\tvideo/mp4\t\n' "$AR_360"
  printf 'lion-desert-1981\t%s\tvideo/mp4\t\n' "$LION_1981"
  printf 'ten-commandments-1923\t%s\tvideo/mp4\t\n' "$TEN_1923"
} > "$MANIFEST_PATH"

if ! command -v cmake >/dev/null 2>&1 || ! command -v c++ >/dev/null 2>&1; then
  echo "Missing build tools. Install build-essential and cmake first." >&2
  exit 3
fi
if ! command -v curl >/dev/null 2>&1; then
  echo "Missing curl, which is required for the smoke test." >&2
  exit 3
fi

cmake -S "$REPO_ROOT/media-server" -B "$BUILD_DIR" -DCMAKE_BUILD_TYPE=Release
cmake --build "$BUILD_DIR" --parallel

SERVER="$BUILD_DIR/hanafi-nougat-media-server"
LOG="$(mktemp)"
cleanup() {
  if [[ -n "${SERVER_PID:-}" ]] && kill -0 "$SERVER_PID" 2>/dev/null; then
    kill "$SERVER_PID" 2>/dev/null || true
    wait "$SERVER_PID" 2>/dev/null || true
  fi
  rm -f "$LOG"
}
trap cleanup EXIT

HANAFI_MEDIA_BIND="$BIND" \
HANAFI_MEDIA_PORT="$PORT" \
HANAFI_MEDIA_MANIFEST="$MANIFEST_PATH" \
HANAFI_MEDIA_CORS_ORIGIN="https://dereksparks1982.github.io" \
"$SERVER" >"$LOG" 2>&1 &
SERVER_PID=$!

for _ in {1..40}; do
  if curl -fsS "http://$BIND:$PORT/nougat/v1/health" >/dev/null 2>&1; then
    break
  fi
  if ! kill -0 "$SERVER_PID" 2>/dev/null; then
    cat "$LOG" >&2
    exit 4
  fi
  sleep .1
done

curl -fsS "http://$BIND:$PORT/nougat/v1/health" | grep -q '"ok":true'
curl -fsS "http://$BIND:$PORT/nougat/v1/catalog" | grep -q 'message-en-720'

check_range() {
  local id="$1"
  local headers
  headers="$(curl -fsSI -H 'Range: bytes=0-1023' "http://$BIND:$PORT/nougat/v1/media?id=$id")"
  grep -qi '^HTTP/1.1 206 ' <<<"$headers"
  grep -qi '^Accept-Ranges: bytes' <<<"$headers"
  grep -qi '^Content-Range: bytes 0-1023/' <<<"$headers"
}

check_range message-en-720
if [[ -f "$EN_1080" ]]; then check_range message-en-1080-hardsubs; fi
check_range risalah-ar-1080
if [[ -f "$AR_1080_HARDSUBS" ]]; then check_range risalah-ar-1080-hardsubs; fi
check_range risalah-ar-480
check_range risalah-ar-360
check_range lion-desert-1981
check_range ten-commandments-1923

curl -fsS "http://$BIND:$PORT/nougat/v1/subtitle?id=risalah-ar-1080" | head -n 1 | grep -q '^WEBVTT'

echo "PASS: Hosted library manifest and Nougat byte-range streaming smoke test."
echo "Manifest: $MANIFEST_PATH"
echo "Server binary: $SERVER"
